### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by kutomer** [Bulisor/BabylonjsDemo#1]
Hello,
I've got to your repo [from](https://forum.babylonjs.com/t/babylonjs-in-reactnative/5420/12) and found it very useful.
I'm currently migrating a [mobile-web game](https://designwithfriends.com/) to Expo and started using your example.

1. I've seen that pinch gesture is working a bit off on iOS devices but when I change: `(this._scale * 60)` to `(this._scale * 0.1)` it gets better, this is just a "magic number" I found that seems to be working better than 60, not 100% sure what it stands for (just started with React Native a day ago) wonder what are you thoughts about that have you tested it on iOS devices?
2. I refactored SceneTemplate from JS to TS, wondered if that's something you need as well if so I'll be happy to create a PR.

**Comment by Bulisor** [comment]
Hey,
1. I'll be honest with you, I tested it only on android. At the very begining (before to add interaction, I think when was only the first scene) I tested it on iOS too, but later I tried to focus only on android. 60 is pretty random, it is working like a speed variable (inverse) a bigger number slow down the speed, and a smaler, increase it, it is up to your need. But this is a good question, maybe I can make it global and setable.
2. Yes, you can do it, this help. 
Thanks!
