### ISSUE TITLE
Error when run example

### ISSUE THREAD

**Issue by jackynguyen93** [Bulisor/BabylonjsDemo#2]
![Screenshot_20200405-185135_Expo](https://user-images.githubusercontent.com/14976555/78479747-897d8000-776f-11ea-9a53-e98bcac94e6a.jpg)
I got this issue when running your example. Maybe some package version causes this error. Here is my package.json file. 
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "~10.0.6",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.3",
    "expo-constants": "~9.0.0",
    "expo-font": "~8.1.0",
    "expo-web-browser": "~8.1.0",
    "expo-asset-utils": "^1.2.0",
    "expo-gl": "^8.1.0",
    "expo-gl-cpp": "^8.1.0",
    "js-base64": "^2.5.1",
    "metro-config": "^0.59.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-unimodules": "~0.5.2",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@babylonjs/core": "^4.1.0-alpha.22",
    "@babylonjs/loaders": "^4.1.0-alpha.22",
    "@babylonjs/materials": "^4.1.0-alpha.22",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~37.0.0",
    "metro-react-native-babel-preset": "0.54.0"
  },
  "private": true
}`
Please help me to resolve this error. Thanks

**Comment by Bulisor** [comment]
Ok, I'll check and let you know

**Comment by jackynguyen93** [comment]
I already resolve this issue (some conflict in npm version), but does it seem not to support gltf2 model yet?

**Comment by Bulisor** [comment]
Great then. It should, but without textures, and not compressed

**Comment by Butterwell** [comment]
> I already resolve this issue (some conflict in npm version), but does it seem not to support gltf2 model yet?

@jackynguyen93 So, how did you fix it, exactly? I've got the same problem.

**Comment by Butterwell** [comment]
You can use the released version of Babylonjs (4.1 of this writing) by adding:

```
class ExpoEngine extends Engine {
    public getHostDocument() {
        return null;
    }
}
```
and then:
`const engine = new ExpoEngine(gl, true, {}, false);
`

**Comment by VrTech** [comment]
@Butterwell  did you solve the issue? please let me know how :(

**Comment by Bulisor** [comment]
@Butterwell answer is a good fix. I updated the repo and the babylonjs library.
I'll update soon the react-native and expo version too.
